name: Daily Email Sender

on:
  # n8n 웹훅을 통한 트리거
  repository_dispatch:
    types: [send-email]
  
  # 기존 cron 스케줄 (필요시 주석 해제)
  # schedule:
  #   - cron: '15 18 * * *'  # 한국 시간 오전 3시 15분
  #   - cron: '25 18 * * *'  # 한국 시간 오전 3시 25분
  #   - cron: '35 18 * * *'  # 한국 시간 오전 3시 35분
  
  workflow_dispatch: # Actions 탭에서 수동으로 실행할 수 있게 함

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set timezone to Asia/Seoul
        run: |
          sudo timedatectl set-timezone Asia/Seoul
          echo "현재 시간: $(date)"

      - name: Run email script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          TZ: Asia/Seoul
          # n8n에서 전달받은 데이터 (옵션)
          WEBHOOK_DATA: ${{ github.event.client_payload.data }}
        run: python send_email.py 